### ISSUE TITLE
Nil pointer deref in runner.run

### ISSUE THREAD

**Issue by y0ssar1an** [timakin/bodyclose#16]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x9a694f]

goroutine 18969 [running]:
github.com/timakin/bodyclose/passes/bodyclose.(*runner).run(0xc0000c6d40, 0xc150d96f00, 0x10, 0xd4f8e0, 0xdf189b62edaedd01, 0xc2d16e0ac0)
	/go/src/github.com/foo/bar/vendor/github.com/timakin/bodyclose/passes/bodyclose/bodyclose.go:57 +0x1af
github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker.(*action).execOnce(0xc06bf7d540)
	/go/src/github.com/foo/bar/vendor/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker/checker.go:382 +0x68a
sync.(*Once).Do(0xc06bf7d540, 0xc00189e790)
	/usr/local/go/src/sync/once.go:44 +0xb3
github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker.(*action).exec(0xc06bf7d540)
	/go/src/github.com/foo/bar/vendor/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker/checker.go:303 +0x50
github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker.execAll.func1(0xc06bf7d540)
	/go/src/github.com/foo/bar/vendor/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker/checker.go:291 +0x34
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker.execAll
	/go/src/github.com/foo/bar/vendor/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker/checker.go:297 +0x11b
```
I encountered this when running `bodyclose` through `golangci-lint`. The stack trace seems to point the finger at [this line](https://github.com/timakin/bodyclose/blob/4a873e97b2bb302885fe7592c4b2d5749cc62985/passes/bodyclose/bodyclose.go#L57). AFAICT `r.resObj.Type()` must be returning `nil`.

Unfortunately, the code that triggered this is private so I can't share it with you 🙁 

```
golangci-lint v1.17.1
go version 1.12.6
```

**Comment by pierrre** [comment]
Same problem.

Strangely, this issue occurred randomly only once.
After running golangci-lint again, I couldn't reproduce the issue.

**Comment by aaron42net** [comment]
I'm having the same issue with bodyclose under golangci-lint.  In case my stack trace is useful somehow:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x9b883f]

goroutine 20790 [running]:
github.com/timakin/bodyclose/passes/bodyclose.(*runner).run(0xc00016c240, 0xc0d5b72d20, 0x10, 0xd6bb00, 0xa5dc4d767ca7de01, 0xc08dc478c0)
	/go/pkg/mod/github.com/timakin/bodyclose@v0.0.0-20190407043127-4a873e97b2bb/passes/bodyclose/bodyclose.go:57 +0x1af
github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker.(*action).execOnce(0xc004107180)
	/go/pkg/mod/github.com/golangci/golangci-lint@v1.17.1/pkg/golinters/goanalysis/checker/checker.go:382 +0x68a
sync.(*Once).Do(0xc004107180, 0xc0012ee790)
	/usr/local/go/src/sync/once.go:44 +0xb3
github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker.(*action).exec(0xc004107180)
	/go/pkg/mod/github.com/golangci/golangci-lint@v1.17.1/pkg/golinters/goanalysis/checker/checker.go:303 +0x50
github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker.execAll.func1(0xc004107180)
	/go/pkg/mod/github.com/golangci/golangci-lint@v1.17.1/pkg/golinters/goanalysis/checker/checker.go:291 +0x34
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker.execAll
	/go/pkg/mod/github.com/golangci/golangci-lint@v1.17.1/pkg/golinters/goanalysis/checker/checker.go:297 +0x11b
```

This is happening intermittently against a large internal codebase, and I haven't been able to carve out a useful test case.
